### ISSUE TITLE
python problems

### ISSUE THREAD

**Issue by mistical2008** [portnov/wacom-intuos-pro-scripts#2]
Hi, i'm tried to launch "ring-mode.py" and then I get such a message 
```
sudo ./ring-mode.py
[sudo] пароль для evgeniy: 
Python libnotify bindings are not available
Namespace(config=None, reset=False)
Traceback (most recent call last):
  File "./ring-mode.py", line 144, in <module>
    config = load_config(args.config)
  File "./ring-mode.py", line 105, in load_config
    config = yaml.safe_load(open(path,'r').read())
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/wacom-ring-modes.yaml'
```
Than I change in "ring-mode.py" load_config path  from:
`~/.config/wacom-ring-modes.yaml`
to staight:
`/home/evgeniy/.config/wacom-ring-modes.yaml`

and then it gives that:
```
[evgeniy@Lenovo-pc bin]$ sudo ./ring-mode.py
Python libnotify bindings are not available
Namespace(config=None, reset=False)
Traceback (most recent call last):
  File "./ring-mode.py", line 145, in <module>
    toggle_mode(config, args.reset)
  File "./ring-mode.py", line 117, in toggle_mode
    profile = get_profile()
  File "./ring-mode.py", line 83, in get_profile
    bus = dbus.SessionBus()
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon aile time, set your DBUS_SESSION_BUS_ADDRESS instead
```
I'm not understand Pyton, and I'm not understand what's going on. My distro is Manjaro(Arch based)

**Comment by mistical2008** [comment]
Need full info for kwin-script install process. I tries run:
`[evgeniy@Lenovo-pc wacom-auto-profile]$ plasmapkg2 --type kwinscript -i wacom-auto-profile
Ошибка установки пакета : Нет такого файла:`
"Installation error: file not found"

**Comment by portnov** [comment]
The last error refers to some DBus error. Never seen such error. Something is not supported. Probably dbus has to be compiled with some flags.

Also, ring-modes.py is designed from unpriviledged user. It only wants to write somewhere under /sys/bus/usb; this right might be given by manual sudo chmod a+w $path, or such chmod can be run from udev rule.

**Comment by mistical2008** [comment]
After [these](https://github.com/portnov/wacom-intuos-pro-scripts/pull/5) changes I try to launch script from CLI. There output:
`[evgeniy@Lenovo-pc python]$ ./ring-mode.py
Python libnotify bindings are not available
Namespace(config=None, reset=False)
xsetwacom list dev
Traceback (most recent call last):
  File "./ring-mode.py", line 145, in <module>
    toggle_mode(config, args.reset)
  File "./ring-mode.py", line 137, in toggle_mode
    set_mode(path, modes[new_mode_idx], new_mode_idx)
  File "./ring-mode.py", line 73, in set_mode
    pad = get_pad_devicename()
  File "./ring-mode.py", line 64, in get_pad_devicename
    m = r.match(line)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by mistical2008** [comment]
After [these](https://github.com/portnov/wacom-intuos-pro-scripts/pull/5) changes I try to launch script from CLI. There output:
```
[evgeniy@Lenovo-pc python]$ ./ring-mode.py
Python libnotify bindings are not available
Namespace(config=None, reset=False)
xsetwacom list dev
Traceback (most recent call last):
  File "./ring-mode.py", line 145, in <module>
    toggle_mode(config, args.reset)
  File "./ring-mode.py", line 137, in toggle_mode
    set_mode(path, modes[new_mode_idx], new_mode_idx)
  File "./ring-mode.py", line 73, in set_mode
    pad = get_pad_devicename()
  File "./ring-mode.py", line 64, in get_pad_devicename
    m = r.match(line)
TypeError: cannot use a string pattern on a bytes-like object
```
